[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "vision-rd"
version = "0.1.0"
description = "Wildfire detection r&d"
authors = [
    "Pyronear <contact@pyronear.org>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyroengine = { git = "https://github.com/pyronear/pyro-engine.git", rev = "main"}

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
