[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "vision-rd"
version = "0.1.0"
description = "Wildfire detection r&d"
authors = [
    "Pyronear <contact@pyronear.org>"
]
readme = "README.md"

[tool.poetry.dependencies]
datasets = "*"
matplotlib = "3.10.0"
pandas = "2.2.3"
python = ">=3.10,<4.0"
pyroengine = { git = "https://github.com/pyronear/pyro-engine.git", rev = "main"}
scikit-learn = "1.6.1"

[tool.poetry.group.dev.dependencies]
pytest = "^5.3.2"
